-- 为dishes表添加新字段
ALTER TABLE IF EXISTS dishes
ADD COLUMN IF NOT EXISTS is_time_limited BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_spicy INTEGER NOT NULL DEFAULT 0, -- 0: 不辣, 1: 微辣, 2: 中辣, 3: 特辣
ADD COLUMN IF NOT EXISTS student_discount NUMERIC(10,2) NOT NULL DEFAULT 0;